# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: ngx1
  name: ngx1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ngx1
  template:
    metadata:
      labels:
        run: ngx1
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: ngx1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ngx1
  name: ngx1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: ngx1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: ngx1
  namespace: default
spec:
  tls:
  - hosts:
    - ngx1.k8s.castlerock.ai
    secretName: ngx1-k8s-tls
  rules:
  - host: ngx1.k8s.castlerock.ai
    http: 
      paths:
      - backend:
          serviceName: ngx1
          servicePort: 80
